// Mocks generated by Mockito 5.4.0 from annotations
// in wordle/test/features/wordle/data/repositories_implementations/random_words_repository_impl/random_words_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wordle/core/core.dart' as _i2;
import 'package:wordle/features/wordle/data/providers/local/words/words_local_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<F extends Object?, V extends Object?> extends _i1.SmartFake
    implements _i2.Result<F, V> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WordsLocalProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordsLocalProvider extends _i1.Mock
    implements _i3.WordsLocalProvider {
  @override
  _i4.Future<_i2.Result<_i2.FetchFailure, List<String>>> getAllWords(
          int? length) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWords,
          [length],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i2.FetchFailure, List<String>>>.value(
                _FakeResult_0<_i2.FetchFailure, List<String>>(
          this,
          Invocation.method(
            #getAllWords,
            [length],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i2.FetchFailure, List<String>>>.value(
                _FakeResult_0<_i2.FetchFailure, List<String>>(
          this,
          Invocation.method(
            #getAllWords,
            [length],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i2.FetchFailure, List<String>>>);
}
